name: 'Colab Badge Action'
author: trsvchn
description: 'Inserts/Updates Colab Badges within Jupyter Notebooks'

inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN secret'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'git-pull-request'
  color: 'yellow'
